export const BRAND_CONTENT = {
  hero: {
    title: 'ESSENCIAL GOOD',
    tagline: 'GOODNESS, MADE ESSENTIAL.',
    subtitle: 'Thoughtfully selected wellness essentials for the routines that matter most.',
    cta: 'EXPLORE THE ESSENTIALS',
    scrollNotice: 'SCROLL TO EXPLORE',
  },
  brandStatement: {
    headline: 'GOODNESS, MADE ESSENTIAL.',
    copy: `Wellness doesn't have to be complicated.\nIt starts with choosing what truly matters.`,
    signature: 'ESSENCIAL GOOD — EVERYDAY WELLNESS, REFINED.',
  },
  whoWeAre: {
    headline: 'WELLNESS, WITH PURPOSE.',
    copyParagraphs: [
      'At Essencial Good, we believe feeling your best should be part of everyday life — not something complicated or overwhelming.',
      'We bring together thoughtfully selected wellness products designed to complement the routines that matter most, from daily balance and metabolic support to rest, beauty and self-care.',
      'Simple choices. Thoughtful essentials. A better way to feel good every day.',
    ],
    cta: 'OUR STORY →',
  },
  meetEssentials: {
    headline: 'MEET THE ESSENTIALS.',
    subheadline: 'Four thoughtfully selected formulas. One simpler approach to everyday wellness.',
  },
  findYourEssential: {
    headline: 'WHAT DOES YOUR ROUTINE NEED?',
    subheadline: 'Start with what matters most to you.',
  },
  customerStories: {
    headline: 'GOOD THINGS ARE WORTH SHARING.',
    subheadline: 'Real routines. Real experiences across the United States.',
    overallRating: '4.98',
    totalReviews: '2,400+',
    testimonials: [
      {
        id: 1,
        author: 'Sarah Jenkins',
        location: 'Austin, TX',
        date: '2 days ago',
        rating: 5,
        topic: 'SlimSODA — Metabolic Support',
        quote: 'SlimSODA has completely replaced my afternoon coffee slump. It is refreshing, light, and gives me that clean energy kick without any jitters. Ordering my 3rd tub today!',
        verified: true,
      },
      {
        id: 2,
        author: 'Marcus Thorne',
        location: 'Seattle, WA',
        date: '3 days ago',
        rating: 5,
        topic: 'Sonnus — Nighttime Rest',
        quote: 'Sonnus is hands down the best nighttime routine addition I have ever tried. I wake up actually feeling rested instead of groggy. 10/10 recommendation!',
        verified: true,
      },
      {
        id: 3,
        author: 'Elena Rostova',
        location: 'Miami, FL',
        date: '1 week ago',
        rating: 5,
        topic: 'Crowned — Beauty & Hair Care',
        quote: 'My hair has not felt this soft and nourished in years. Crowned is pure luxury in a bottle — it absorbs so fast and smells amazing.',
        verified: true,
      },
      {
        id: 4,
        author: 'David Miller',
        location: 'San Diego, CA',
        date: '1 week ago',
        rating: 5,
        topic: 'LinfaFlow — Daily Balance',
        quote: 'LinfaFlow made my daily morning self-care routine feel effortless. I have noticed a huge difference in my overall lightness and daily digestive flow.',
        verified: true,
      },
      {
        id: 5,
        author: 'Claire Vance',
        location: 'Boston, MA',
        date: 'August 14, 2026',
        rating: 5,
        topic: 'Fast 2-Day Shipping',
        quote: 'Shipped to Boston in less than 48 hours! The packaging feels like opening an unboxing experience from a Beverly Hills boutique. Extremely impressed.',
        verified: true,
      },
      {
        id: 6,
        author: 'Hannah Brooks',
        location: 'Denver, CO',
        date: 'August 11, 2026',
        rating: 5,
        topic: 'SlimSODA — Daily Routine',
        quote: 'Finally a soda alternative that actually tastes incredible and supports my metabolic routine. It has become a permanent staple on my kitchen counter.',
        verified: true,
      },
      {
        id: 7,
        author: 'Jonathan Cole',
        location: 'New York, NY',
        date: 'August 08, 2026',
        rating: 5,
        topic: 'Customer Experience',
        quote: 'Had a quick question about my subscription and customer care responded in under 15 minutes with a solution. True high-end service.',
        verified: true,
      },
      {
        id: 8,
        author: 'Rachel Sterling',
        location: 'Chicago, IL',
        date: 'August 05, 2026',
        rating: 5,
        topic: 'Sonnus — Sleep Reset',
        quote: 'I travel constantly for work between NYC and Chicago. Sonnus has been a lifesaver for resetting my sleep schedule on hotel nights.',
        verified: true,
      },
      {
        id: 9,
        author: 'Jessica Albright',
        location: 'Nashville, TN',
        date: 'August 02, 2026',
        rating: 5,
        topic: 'Crowned & LinfaFlow',
        quote: 'I bought the bundle for Crowned and LinfaFlow. My daily hair and wellness ritual is now something I genuinely look forward to every single morning.',
        verified: true,
      },
      {
        id: 10,
        author: 'Matthew Hayes',
        location: 'Portland, OR',
        date: 'July 28, 2026',
        rating: 5,
        topic: 'Full Essentials Collection',
        quote: 'I started with SlimSODA and ended up getting all 4 products. Essencial Good really nailed the minimalist, high-quality wellness aesthetic.',
        verified: true,
      },
    ],
  },
  guarantee: {
    headline: 'TRY IT WITH CONFIDENCE.',
    number: '90',
    label: 'DAY GUARANTEE',
    copy: "We're confident in the quality of Essencial Good and want you to feel comfortable making it part of your routine.",
    cta: 'LEARN ABOUT OUR GUARANTEE →',
    disclaimer: 'Terms and conditions apply. Subject to official guarantee policy details.',
  },
  physicalStore: {
    headline: 'GOODNESS, MADE REAL.',
    copy: "Essencial Good is more than an online destination. It's a brand built around making everyday wellness feel simple, intentional and accessible.",
    cta: 'VISIT ESSENCIAL GOOD',
    secondaryCta: 'FIND US',
    addressPlaceholder: 'Flagship Location — Details & Address to be specified',
  },
  faq: {
    headline: 'QUESTIONS, ANSWERED.',
    items: [
      {
        id: 'faq-1',
        question: 'What is Essencial Good and how do your 4 formulas work together?',
        answer: 'Essencial Good is a modern wellness brand offering 4 targeted daily essentials — SlimSODA (Body), LinfaFlow (Balance), Sonnus (Rest), and Crowned (Beauty). Each formula is thoughtfully crafted to complement your existing habits without overwhelming your schedule.',
      },
      {
        id: 'faq-2',
        question: 'Can I integrate multiple Essencial Good products into my daily routine?',
        answer: 'Yes. Our collection is specifically designed to work harmoniously together throughout your day — for example, taking SlimSODA in the morning, LinfaFlow midday, Crowned for daily hair care, and Sonnus to prepare for nighttime rest.',
      },
      {
        id: 'faq-3',
        question: 'How fast will my order be processed and shipped?',
        answer: 'All orders are processed within 24 hours. Standard US domestic shipping delivers to your doorstep within 2–4 business days, complete with real-time tracking information sent directly to your email.',
      },
      {
        id: 'faq-4',
        question: 'How does the 90-Day Money-Back Guarantee work?',
        answer: 'We want you to try Essencial Good with 100% peace of mind. You have 90 full days to incorporate our products into your daily routine. If you are not completely satisfied with your experience, contact our care team for a hassle-free refund.',
      },
      {
        id: 'faq-5',
        question: 'Where are Essencial Good formulas manufactured and quality-tested?',
        answer: 'All Essencial Good formulas are meticulously developed and manufactured in cGMP-certified, FDA-registered facilities in the United States, adhering strictly to modern purity standards and quality control protocols.',
      },
    ],
  },
  finalCta: {
    headline: 'MAKE WELLNESS ESSENTIAL.',
    copy: 'Better routines begin with simple choices.',
    primaryCta: 'EXPLORE THE ESSENTIALS',
    secondaryCta: 'OUR STORY',
  },
  footer: {
    logo: 'ESSENCIAL GOOD',
    tagline: 'Everyday wellness, refined.',
    copyright: '© 2026 Essencial Good. All rights reserved.',
  },
};
